#!/bin/bash
# ANCP Spreadsheet MicroService
# /etc/init.d/ancp-spreadsheet-ms

### BEGIN INIT INFO
# Provides:          ANCP Spreadsheet MicroService
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ANCP Spreadsheet MicroService Start/Stop Script
# Description:       MicroService for ANCP Spreadsheet handling
### END INIT INFO

API_KEY="your_api_key" # Replace with your actual API key
ISPRODUCTION=false     

# Path to your conda environment (one for production and one for development)
if [[ $ISPRODUCTION = true ]]
then
    MS_USER="ancp"
else
    MS_USER="llouzada"
fi

FLASK_APP="/home/$MS_USER/projects/spreadsheet-ms/app/main.py"
CONDA_SH_PATH="/home/$MS_USER/miniconda3/etc/profile.d/conda.sh"
CONDA_ENV_NAME="spreadsheet-ms-env"

case "$1" in
    start)
        echo "Starting ancp-spreadsheet-ms..."
        source "$CONDA_SH_PATH"  # Sourcing the conda setup
        conda activate "$CONDA_ENV_NAME"  # Activate the conda environment
        export MS_API_KEY="$API_KEY"
        nohup python3 "$FLASK_APP" >> /var/log/ancp-spreadsheet-ms.log 2>&1 &
        ;;
    stop)
        echo "Stopping ancp-spreadsheet-ms..."
        pkill -f "$FLASK_APP"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: /etc/init.d/ancp-spreadsheet-ms {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
